version: "3.8"

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
    ports:
      - "5432:5432"
    networks:
      - web_app
      
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    networks:
      - web_app

  proxy:
    image: nginx:latest
    volumes:
      - ./default.conf.tpl:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - app
    networks:
      - web_app

networks:
  web_app:

volumes:
  postgres:
