version: "3.8"

services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - web_app

  django:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - web_app
    depends_on:
      - postgres
    environment:
      - DJANGO_DEBUG=1
      
networks:
  web_app:

volumes:
  postgres:
