version: "3.8"

services:
  django:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - web_app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_app
    depends_on:
      - django
      
networks:
  web_app:
  nginx:
