# Generated by Django 5.0.7 on 2024-08-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
