# Generated by Django 5.0.7 on 2024-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_consultation_is_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="status",
        ),
        migrations.AddField(
            model_name="slot",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
