# Generated by Django 5.0.7 on 2024-08-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_remove_slot_status_slot_is_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                help_text="There might be many bookings for a Meeting duration",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="consultations.slot",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
