# Generated by Django 5.0.7 on 2024-08-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0004_alter_booking_slot_alter_booking_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                help_text="There might be many bookings for single slot",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="consultations.slot",
            ),
        ),
    ]
