# Generated by Django 5.1 on 2024-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0006_booking_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="description",
        ),
        migrations.AddField(
            model_name="consultation",
            name="content_path",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
