# Generated by Django 5.0.7 on 2024-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="categorization.tag"
            ),
        ),
    ]
