# Generated by Django 5.0.7 on 2024-08-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categorization", "0002_remove_tag_category_category_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="categorization.category",
            ),
            preserve_default=False,
        ),
    ]
