# Generated by Django 5.0.7 on 2024-08-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categorization", "0003_remove_category_tags_tag_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
