# Generated by Django 5.0.7 on 2024-07-18 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=50,
                    ),
                ),
                ("to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("html", models.TextField()),
                ("plain_text", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="email",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sent_at__isnull", True), ("status", "SENT"), _connector="OR"
                ),
                name="check_email_sent_at_with_status",
            ),
        ),
    ]
